mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create/$', views.CreateView.as_view(), name='create'),
    url(r'^created/$', views.create, name='created'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditView.as_view(), name='edit'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<question_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<question_id>[0-9]+)/edit/$', views.edit, name='edit')
]

polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Choice(models.Model):
    choice_text=models.CharField(max_length=200)

    @staticmethod
    def get(c): #returns the choice or makes a new one if it doesn't exist
        choice = Choice.objects.filter(choice_text=c)
        if len(choice) > 0:
            return choice[0]
        else:
            return Choice(choice_text=choice)

    def __str__(self):
        return self.choice_text

class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')
    choice_set = models.ManyToManyField('Choice', through='Vote', related_name='choices')
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def removeChoice(self,choice):
        vote=Vote.get(q=self,c=choice)
        Vote.get(q=self, c=choice).delete()

    def addChoice(self,choice):
        self.save()
        Vote.addVote(q=self,c=choice,amnt=0)

    def removeAllChoices(self):
        for choice in self.choice_set.all():
            self.removeChoice(choice)



    def __str__(self):
        return self.question_text


class Vote(models.Model):
    question = models.ForeignKey(Question, related_name='votes')
    choice = models.ForeignKey(Choice, related_name='votes')
    votes = models.IntegerField(default=0)

    @staticmethod
    def addVote(q,c,amnt=1):
        connection=Vote.get(q=q,c=c)
        q.save()
        c.save()

        if connection is None:
            return Vote.objects.create(question=q, choice=c, votes=amnt)
        else:
            connection.increaseVote(amnt=amnt)
            connection.save()
            return connection

    @staticmethod
    def get(q,c):
        q=Question.objects.filter(question_text=q)
        c=Choice.get(c=c)
        v=Vote.objects.filter(question=q, choice=c)
        if len(v) > 0:
            return v[0]
        else:
            return None

    def increaseVote(self,amnt):
        self.votes+=amnt

    def __str__(self):
        return self.question.question_text + ' ' + self.choice.choice_text + ' '+ str(self.votes)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Question
from django.views import generic
from django.utils import timezone

from .models import *
from django import forms
from django .forms import formset_factory


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')


class CreateView(generic.ListView):
    template_name = 'polls/create.html'
    context_object_name = 'create_question'
    def get_queryset(self):
        return Question.objects


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class EditView(generic.DetailView):
    model = Question
    template_name = 'polls/edit.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    print(request)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        vote=Vote.get(q=question,c=selected_choice)
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        vote.votes += 1
        vote.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def edit(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    question.question_text=request.POST['question_text']
    question.removeAllChoices()
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def create(request):
    question=Question(question_text=request.POST['question_text'])
    question.pub_date=timezone.now()
    choice_count=int(request.POST['choice_count'])
    print(choice_count)

    for x in range(0,choice_count):
        name='choice'+str(x)
        choice=Choice(choice_text=request.POST[name])
        Vote.addVote(q=question,c=choice, amnt=0)

    list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    context_object_name = {'latest_question_list': list}
    return render(request, 'polls/index.html', context_object_name)



def delete(request, question_id):
    question=Question.objects.get(id=question_id)
    question.delete()

    list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    context_object_name = {'latest_question_list': list}
    return render(request, 'polls/index.html', context_object_name)

def get_index(self,request): #replacing the 3 lines above with this function doesn't work for some reason
    list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    context_object_name = {'latest_question_list': list}
    return render(request, 'polls/index.html', context_object_name)

polls/templates/polls/create.html
{%load static%}
<head>
    <script type="text/javascript" src="{%static 'polls/create.js'%}"></script>
    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
    <style>
        #question{
            font-size: 18px;
        }
    </style>
</head>

<h1>Create question:</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:created'%}" method="post">
{% csrf_token %}
<textarea name="question_text" id="question" rows="2" cols="50"></textarea>
</br>
<b>Choices:</b>
<ul id="choices" name="choices">
    <li id="choice0">
        <input name="choice0" type="text"> <input type='button' onclick="removeChoice('choice0')" value="Remove">
    </li>
</ul>
<input type="text" id="choice_count" name="choice_count" value="1" hidden>
<br>
<input type="button" onclick="addChoice()" value="+">
<input type="submit" value="Create"/>
</form>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/edit.html
<head>
    <style>
        #question{
            font-size: 18px;
        }
    </style>
</head>

<h1>Edit question:</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:edit' question.id %}" method="post">
{% csrf_token %}
<textarea id="question" rows="2" cols="50">{{question.question_text }}</textarea>
{% for choice in question.choice_set.all %}
    </br>
    <input type="text" name="choice" value="{{ choice.choice_text }}">
{% endfor %}
</br>
<input type="submit" value="Edit"/>
</form>

polls/templates/polls/index.html
{%load static%}
<head>
<link rel="stylesheet" type="text/css" href="{%static 'polls/styles.css'%}"/>
</head>

{% if latest_question_list %}
<table style="width:100%;">
    {% for question in latest_question_list %}
    <tr>
        <td><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></th>
        <td><a href="{% url 'polls:edit' question.id %}">Edit</a></th>
        <td><a href="{% url 'polls:delete' question.id %}">Delete</a></th>
    </tr>
    {% endfor %}
</table>
{% else %}
<br>
<p>No polls are available.</p>
{% endif %}
<button><a href="{% url 'polls:create'%}">Create</a></button>

polls/templates/polls/results.html
{%load poll_extras%}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {% getVotes question choice %}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>